### ISSUE TITLE
Recover Error

### ISSUE THREAD

**Issue by MattiMo79** [jivanpal/apfs-tools#79] opened 2024-03-03 17:53 UTC
Hi Jivan
Your program is amazing!! I managed to recover some files, but i have a small problem with restoring the folders... After reading the folder with the list command, when i try to restore the folders appears this error:

This inode is multilinked. Do you still want to recover the file data? (y/n) y
ERROR: get_file_size: No file size found.

![image](https://github.com/jivanpal/drat/assets/162047743/a569c168-088e-4466-8942-f3b0222d0c47)

What could it depend on?
I use Ubuntu 20.04 Lts Live

Thank You for support

**Comment by jivanpal** [comment] 2024-03-04 01:04
Hi, I'm afraid Drat doesn't currently support recursively recovering files from directories; you'll have to recover each file individually. This feature request is being tracked in #67.

Please refer to #30 for guidance on automating recovery for now. I'll be closing this as a duplicate of that.

**Closed as completed by jivanpal** 2024-03-04 01:04 UTC
Labels: duplicate
